# Environment variables
language: c
arch: arm64
cache:
  ccache: true
  pip: true
dist: bionic
osx_image: xcode11.2
env: build_type=release
addons:
  apt:
    sources:
    packages: cmake yasm valgrind libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev python-pip python3-pip

# Default scripts
before_install:
  - "sudo chown -R travis: $HOME/.ccache"
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig PATH="/usr/local/opt/ccache/libexec:$PATH"
  - cd $TRAVIS_BUILD_DIR
  - wget -nc https://raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master/video.tar.gz || wget -nc http://randomderp.com/video.tar.gz
  - tar xf video.tar.gz
  - mkdir -p $TRAVIS_BUILD_DIR/Build/linux/${build_type:-Release}
  - if [ $CC = "/usr/bin/gcc-8" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get install -qq gcc-8 g++-8; fi
  - if [ $CC = "/usr/bin/gcc-9" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get install -qq gcc-9 g++-9; fi
  - if [ "$CC" != "clang" -a "$CC" != "gcc" ]; then sudo ln -s /usr/bin/ccache /usr/lib/ccache/${CC##*/} || true; fi
  - if [ "$CXX" != "clang++" -a "$CXX" != "g++" ]; then sudo ln -s /usr/bin/ccache /usr/lib/ccache/${CXX##*/} || true; fi
install:
  - export PATH=/Users/travis/Library/Python/2.7/bin:${PATH}
  - |
    if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      export CFLAGS="-Werror"
      if [ "$CC" = "clang" ]; then export CFLAGS+=" -Wno-error=array-bounds"; fi
    fi
  #- if [ $TRAVIS_OS_NAME = osx ]; then brew install --HEAD valgrind; fi
base_script: &base_script |
  cd $TRAVIS_BUILD_DIR/Build/linux/${build_type:-Release}
  cmake $TRAVIS_BUILD_DIR -G"${generator:-Unix Makefiles}" -DCMAKE_BUILD_TYPE=${build_type:-Release} ${CMAKE_EFLAGS[@]}
  cmake -j $(if [ $TRAVIS_OS_NAME = osx ]; then sysctl -n hw.ncpu; else nproc; fi) --build . &&
  sudo cmake --build . --target install && cd $TRAVIS_BUILD_DIR
script:
  - *base_script
  - SvtAv1EncApp -enc-mode 8 -w 720 -h 486 -fps 60 -i akiyo_cif.y4m -n 150 -b test1.ivf
before_cache:
  - "sudo chown -R travis: $HOME/.ccache"

# Build matrix
matrix:
  fast_finish: true
  include:
    # Coding style check
    - name: Style check
      addons: skip
      before_install: skip
      install: skip
      script:
        - git remote rm upstream 2> /dev/null || true
        - git remote add upstream https://github.com/OpenVisualCloud/SVT-AV1.git
        - git fetch -q upstream master
        - git grep -InP --heading "\t" -- . ':!third_party/**/*' && false || true
        - git grep -InP --heading "\r" -- . ':!third_party/**/*' && false || true
        - git grep -InP --heading " $" -- . ':!third_party/**/*' && false || true
        - |
          for file in $(git ls-tree --name-only -r HEAD |
            grep -vE "third_party/|test/e2e_test/test_vector_list.txt|test/vectors/smoking_test.cfg|test/vectors/video_src.cfg|.png"); do
            if [ -n "$(tail -c1 "$file")" ]; then
              echo "No newline at end of $file"
              false
            fi
          done
          for i in $(git rev-list HEAD ^upstream/master); do
            echo "Checking commit message of $i"
            msg="$(git log --format=%B -n 1 $i)"
            if [ -n "$(sed -n 2p <<<"$msg")" ]; then
              echo "Malformed commit message in $i, second line must be empty"
              false
            fi
            if head -1 <<<"$msg" | grep -q '\.$'; then
              echo "Malformed commit message in $i, trailing period in subject line"
              false
            fi
          done
    # GCC & Clang builds
    - name: Linux GCC 7 build
    - name: Linux GCC 8 build
      env: build_type=release CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8
    - name: Linux GCC 9 build
      env: build_type=release CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9
    - name: Linux Clang build
      compiler: clang
    # FFmpeg interation build
    - name: FFmpeg patch
      env: build_type=release
      script:
        # Build and install SVT-AV1
        - *base_script
        # Apply SVT-AV1 plugin and enable libsvtav1 to FFmpeg
        - git clone https://github.com/FFmpeg/FFmpeg --branch release/4.2 --depth=1 ffmpeg && cd ffmpeg
        - git apply $TRAVIS_BUILD_DIR/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
        - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig
        - "sudo chown -R travis: $HOME/.ccache"
        - export CFLAGS=""
        - ./configure --enable-libsvtav1 || less ffbuild/config.log
        - make --quiet -j$(nproc) && sudo make install
    # GStreamer interation build
    - name: GStreamer patch
      env: build_type=release
      script:
      # Build and install SVT-AV1
      - *base_script
      # Build GST-SVT-AV1 plugin
      - cd $TRAVIS_BUILD_DIR/gstreamer-plugin
      - "sudo chown -R travis: $HOME/.ccache"
      - CFLAGS=""
      - cmake .
      - make --quiet -j$(nproc)
      - sudo make install
    # Tests if .ivf files are identical on binary level
    - name: Binary Identical?
      script:
        - mv -t $HOME akiyo_cif.y4m
        - *base_script
        - cd $HOME
        - SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 120 -b test-pr-m8.ivf
        - SvtAv1EncApp -enc-mode 0 -i akiyo_cif.y4m -n 3 -b test-pr-m0.ivf
        - rm -rf $TRAVIS_BUILD_DIR
        - git clone --depth 1 https://github.com/OpenVisualCloud/SVT-AV1.git $TRAVIS_BUILD_DIR
        - cd $TRAVIS_BUILD_DIR
        - mkdir -p $TRAVIS_BUILD_DIR/Build/linux/${build_type:-Release}
        - *base_script
        - cd $HOME
        - SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 120 -b test-master-m8.ivf
        - SvtAv1EncApp -enc-mode 0 -i akiyo_cif.y4m -n 3 -b test-master-m0.ivf
        - diff test-pr-m8.ivf test-master-m8.ivf
        - diff test-pr-m0.ivf test-master-m0.ivf

    # Valgrind on Linux and macOS
    - name: Valgrind
      env: build_type=debug
      script:
        - *base_script
        - valgrind -- SvtAv1EncApp -enc-mode 2 -w 720 -h 486 -fps 60 -i akiyo_cif.y4m -n 20 -b test1.ivf

    # Unittests on Linux and macOS
    - name: Unit Tests Linux+gcc
      env: build_type=release CMAKE_EFLAGS="-DBUILD_TESTING=ON" SVT_AV1_TEST_VECTOR_PATH=$TRAVIS_BUILD_DIR/test/vectors/
      script:
        - *base_script
        - cd $TRAVIS_BUILD_DIR/Build/linux/${build_type:-Release}
        - make TestVectors
        - cd $TRAVIS_BUILD_DIR
        - SvtAv1UnitTests
        - SvtAv1ApiTests
        - SvtAv1E2ETests
